# Generated by Django 2.2.7 on 2019-11-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_original_title'),
        ('accounts', '0002_auto_20191124_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, related_name='like_movie_users', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='message',
            name='movie',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='like_genre_users', to='movies.Genre'),
        ),
    ]
