# Generated by Django 2.2.7 on 2019-11-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191125_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Message'),
            preserve_default=False,
        ),
    ]
