# Generated by Django 2.2.7 on 2019-11-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genreId',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
