# Generated by Django 2.2.7 on 2019-11-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191125_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
