# Generated by Django 2.2.7 on 2019-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_original_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='character_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='teaser',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
